\input texinfo.tex
@c This file is part of the Neper software package.
@c Copyright (C) 2003-2019 Romain Quey
@c See the COPYING file in the top-level directory.

@afourpaper
@c =========================================================================
@c
@c This is the Neper documentation texinfo source file
@c
@c =========================================================================
@c %**start of header
@setfilename        neper.info
@include version.texi
@set COPYRIGHT @copyright{} 2003--2019 Romain Quey
@c
@settitle Neper @value{NEPER_VERSION}
@footnotestyle separate
@setchapternewpage odd
@paragraphindent 0
@finalout
@c

@c merge function index into type index
@syncodeindex fn tp

@c =========================================================================
@c Info directives
@c =========================================================================

@ifinfo
@dircategory Math
@direntry
* Neper: (neper). Polycrystal generation and meshing
@end direntry
@noindent
This is the @cite{Neper Reference Manual} for Neper @value{NEPER_VERSION}
(@today{}).
@noindent
Copyright @value{COPYRIGHT}
@end ifinfo

@c =========================================================================
@c Title page
@c =========================================================================

@c @shorttitlepage Neper

@titlepage

@title Neper Reference Manual

@subtitle The documentation for Neper @value{NEPER_VERSION}
@subtitle A software package for polycrystal generation and meshing
@subtitle @*
@subtitle @today{}
@c @subtitle Edition @value{NEPER_VERSION} @today{}

@author Romain Quey

@page
@vskip 0pt plus 1filll
Copyright @value{COPYRIGHT}

@sp 1
Permission is granted to make and distribute verbatim copies of this manual
provided the copyright notice and this permission notice are preserved on
all copies.

@end titlepage

@c =========================================================================
@c Table of contents
@c =========================================================================

@c @summarycontents
@contents

@c =========================================================================
@c Top node (for all output, except TeX)
@c =========================================================================

@ifnottex
@node Top
@top Neper

Romain Quey

Neper is a software package for polycrystal generator and meshing.
This is the @cite{Neper Reference Manual} for Neper
@value{NEPER_VERSION} (@today{}).
@end ifnottex

@c =========================================================================
@c Master menu
@c =========================================================================

@menu
* Conditions of Use::
* Introduction::
* Tessellation Module (-T)::
* Meshing Module (-M)::
* Visualization Module (-V)::
* Expressions and Keys::
* File Formats::
* Developer's Guide::
* Versions::
* GNU General Public License::
* Option Index::
@end menu

@c DEFINING MACROS

@c NEPER
@macro neper
Neper
@end macro

@macro mT
@w{module -T}
@end macro

@macro mM
@w{module -M}
@end macro

@macro mV
@w{module -V}
@end macro

@macro MT
@w{Module -T}
@end macro

@macro MM
@w{Module -M}
@end macro

@macro MV
@w{Module -V}
@end macro

@macro SEPNODEP
,
@end macro

@macro SEPDEP
:
@end macro

@macro SEPFRAC
::
@end macro

@macro mybullet
@math{@bullet{}}@w{ }
@end macro

@c COM
@macro com{a}
@iftex
@sp 0
@ @phantom{XX}
@t{$} @code{\a\}
@end iftex
@ifinfo
$ \a\
@end ifinfo
@end macro

@c COM
@macro comc{a,b}
@iftex
@sp 0
@ @phantom{XX}
@t{$} @code{\a\} \b\
@end iftex
@ifinfo
$ \a\ \b\
@end ifinfo
@end macro

@macro comx{a}
@iftex
@sp 0
@ @phantom{XX}
@phantom{@t{$}} @code{\a\}
@ @phantom{XX}
@sp 0
@end iftex
@ifinfo
$ \a\
@end ifinfo
@end macro

@c @macro comx{a}
@c @multitable @columnfractions 0.05 0.95
@c @item
@c @tab @t{ } @t{\a\}
@c @end multitable
@c @end macro

@c @tab @t{@phantom{$}} @t{\a\}

@c below, @var has been change to @emph because makeinfo does not
@c tolerate `[' charaacters in @var{}, while it is used for optional
@c arguments.

@c REQ
@macro req{a, e, b, c, d }
@deftypefn {Prerequisite} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c OPT
@macro opt{a, e, b, c, d }
@kindex \a\
@deftypefn {Option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c OPTTWO
@macro opttwo{f, g, a, e, b, c, d }
@kindex \f\
@kindex \g\
@deftypefn {Option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c OPTTWOSEC
@macro opttwosec{f, g, a, e, b, c, d }
@kindex \f\
@kindex \g\
@deftypefn {Secondary Option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c SOPT
@macro optsec{a, e, b, c, d }
@kindex \a\
@deftypefn {Secondary option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c SOPT
@macro optnrc{a, e, b, c, d }
@kindex \a\
@deftypefn {Not recommended option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c SOPT
@macro optdis{a, e, b, c, d }
@kindex \a\
@deftypefn {Disabled option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c SOPT
@macro optsectwo{f, g, a, e, b, c, d }
@kindex \f\
@kindex \g\
@deftypefn {Secondary option} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c OPTF
@macro optf{a, f, b, c, d, e}
@kindex \a\
@deftypefn {Option} @t{\a\} @emph{\f\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.@*
Result file: extension @file{\e\}.
@end deftypefn
@end macro

@c INPUT
@c for some odd reasons, @kindex cannot be inserted here.
@c They are inserted in the body of the text instead.
@macro inp{a, e, b, c, d }
@deftypefn {Input data} @t{\a\} @emph{\e\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.
@end deftypefn
@end macro

@c POST
@macro post{a, f, b, c, d, e}
@kindex \a\
@deftypefn {Post-processing} @t{\a\} @emph{\f\}
\b\@*
Possible values: @code{\c\}. Default value: @code{\d\}.@*
Result file: extension @file{\e\}.
@end deftypefn
@end macro

@include copying.texi
@include introduction.texi
@include neper_t.texi
@include neper_m.texi
@include neper_v.texi
@include exprskeys.texi
@include fileformat.texi
@include develguide.texi
@include versions.texi
@include license.texi

@node Option Index
@unnumbered Option Index
@printindex ky
@c for some odd reasons, it does not work with a function index
@c (@findex and fn)

@bye
