#!/bin/bash

status=0

if [ "$NEPERROOT" == "" ]
then
  echo "Environment variable NEPERROOT not set.  You need to set it to NEPER's root directory."
  exit -1
fi

git commit $1
status="$?"

date=`date +"%d %b %G"`
tag=`git describe --match "*start" | grep start | awk -F- '{print $1}' | sed -e "s/\<v//g"`
id=` git describe --match "*start" | grep start | awk -F- '{print $3}'`

if [ "$tag" == "" ]
then
  echo "Failed to find start tag."
  exit -1
fi

branch=`git status | head -1 | awk '{print $3}'`

if [ "$branch" == "main" ]
then
  version="$tag-$id"
else
  version="$tag-$id-$branch"
fi

if [ "$status" != "0" ]
then
  echo Version $version
  exit $status
fi

sed -i "1s/.*/New in $version ($date):/g" $NEPERROOT/VERSIONS
vi $NEPERROOT/VERSIONS
version2=`echo $version | sed -e "s/_/@&/g"`
sed -i "1,100s/@set NEPER_VERSION.*/@set NEPER_VERSION $version2/g" $NEPERROOT/doc/texinfo/version.texi
sed -i "1,100s/set(NEPER_VERSION.*/set(NEPER_VERSION \\\\\"$version\\\\\")/g" $NEPERROOT/src/CMakeLists.txt
git add $NEPERROOT/VERSIONS $NEPERROOT/doc/texinfo/version.texi $NEPERROOT/src/CMakeLists.txt
git commit --amend --no-edit > /dev/null
status="$?"

if [ "$status" == "0" ]
then
  echo "Updated version to $version."
else
  echo "Failed to update version to $version.  Something nasty happened:"
  git status
  exit 1
fi

exit 0
