#!/bin/bash

# This file is part of the Neper software package.
# Copyright (C) 2003-2020, Romain Quey.
# See the COPYING file in the top-level directory.

status=0

git commit $1
status="$?"

date=`date +"%d %b %G"`
tag=`git describe | grep start | awk -F- '{print $1}'`
id=` git describe | grep start | awk -F- '{print $3}'`

if [ "$tag" == "" ]
then
  echo "Failed to find start tag."
  exit -1
fi

branch=`git status | head -1 | awk '{print $3}'`

if [ "$branch" == "devel" ]
then
  version="$tag-$id"
else
  version="$tag-$id-$branch"
fi

if [ "$status" != "0" ]
then
  echo Version $version
  exit $status
fi

sed -i "1s/.*/New in $version ($date):/g" $NEPER/../VERSIONS
vi $NEPER/../VERSIONS
version2=`echo $version | sed -e "s/_/@&/g"`
sed -i "1,100s/@set NEPER_VERSION.*/@set NEPER_VERSION $version2/g" $NEPER/../doc/texinfo/version.texi
sed -i "1,100s/set (NEPER_VERSION.*/set (NEPER_VERSION \\\\\"$version\\\\\")/g" $NEPER/CMakeLists.txt
git add $NEPER/../VERSIONS $NEPER/../doc/texinfo/version.texi $NEPER/CMakeLists.txt
git commit --amend --no-edit > /dev/null
status="$?"

if [ "$status" == "0" ]
then
  echo "Updated version to $version."
else
  echo "Failed to update version to $version.  Something nasty happened:"
  git status
  exit 1
fi

exit 0
